POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Hello World Blog",
  "author": "Henry Lin",
  "url": "helloworldblog.com",
  "likes": "15",
  "userId": "5f1617523269ae0194135fd3"
}